export const CREATE_SESSION = '/api/v1/session/create'
export const WIDGET_TOKEN = '/api/v1/token'
export const BALANCE = '/api/v1/wallet/balance'
export const CANCEL_PAYMENT = '/api/v1/session/cancel'
export const CONFIRM_PAYMENT = '/api/v1/session/confirm'